
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef MASTERNODE_SENSOR_H
#define MASTERNODE_SENSOR_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 MasterNode_Sensor_valueRangeTest (UNS8 typeValue, void * value);
const indextable * MasterNode_Sensor_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data MasterNode_Sensor_Data;
extern REAL32 Temperature[30];		/* Mapped at index 0x2000, subindex 0x01 - 0x1E */
extern REAL32 Humidity[30];		/* Mapped at index 0x2001, subindex 0x01 - 0x1E */

#endif // MASTERNODE_SENSOR_H
