
/* File generated by gen_cfile.py. Should not be modified. */

#include "MasterNode_Sensor.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
REAL32 Temperature[] =		/* Mapped at index 0x2000, subindex 0x01 - 0x1E */
  {
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000
  };
REAL32 Humidity[] =		/* Mapped at index 0x2001, subindex 0x01 - 0x1E */
  {
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000
  };

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 MasterNode_Sensor_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 MasterNode_Sensor_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 MasterNode_Sensor_iam_a_slave = 0;

TIMER_HANDLE MasterNode_Sensor_heartBeatTimers[30] = {TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE};

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 MasterNode_Sensor_obj1000 = 0x0;	/* 0 */
                    subindex MasterNode_Sensor_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1000, NULL }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 MasterNode_Sensor_obj1001 = 0x0;	/* 0 */
                    subindex MasterNode_Sensor_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1001, NULL }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    subindex MasterNode_Sensor_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1003, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1003[0], NULL }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 MasterNode_Sensor_obj1005 = 0x40000080;	/* 1073741952 */
                    subindex MasterNode_Sensor_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1005, NULL }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 MasterNode_Sensor_obj1006 = 0xC350;	/* 50000 */
                    subindex MasterNode_Sensor_Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1006, NULL }
                     };

/* index 0x1007 :   Synchronous Window Length. */
                    UNS32 MasterNode_Sensor_obj1007 = 0x3E8;	/* 1000 */
                    subindex MasterNode_Sensor_Index1007[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1007, NULL }
                     };

/* index 0x100C :   Guard Time */ 
                    UNS16 MasterNode_Sensor_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 MasterNode_Sensor_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID */
                    UNS32 MasterNode_Sensor_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1016 = 30; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1016[] = 
                    {
                      0x3E8,	/* 1000 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex MasterNode_Sensor_Index1016[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1016, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1016[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1016[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1016[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1016[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1016[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1016[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1016[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1016[7], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1016[8], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1016[9], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1016[10], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1016[11], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1016[12], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1016[13], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1016[14], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1016[15], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1016[16], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1016[17], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1016[18], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1016[19], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1016[20], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1016[21], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1016[22], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1016[23], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1016[24], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1016[25], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1016[26], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1016[27], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1016[28], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1016[29], NULL }
                     };

/* index 0x1017 :   Producer Heartbeat Time */ 
                    UNS16 MasterNode_Sensor_obj1017 = 0x0;   /* 0 */

/* index 0x1018 :   Identity. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 MasterNode_Sensor_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 MasterNode_Sensor_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 MasterNode_Sensor_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex MasterNode_Sensor_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1018, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1018_Vendor_ID, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1018_Product_Code, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1018_Revision_Number, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1018_Serial_Number, NULL }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1400_COB_ID_used_by_PDO = 0x181;	/* 385 */
                    UNS8 MasterNode_Sensor_obj1400_Transmission_Type = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex MasterNode_Sensor_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1400, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1400_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1400_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1400_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1400_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1400_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1400_SYNC_start_value, NULL }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1401_COB_ID_used_by_PDO = 0x182;	/* 386 */
                    UNS8 MasterNode_Sensor_obj1401_Transmission_Type = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex MasterNode_Sensor_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1401, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1401_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1401_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1401_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1401_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1401_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1401_SYNC_start_value, NULL }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1402_COB_ID_used_by_PDO = 0x185;	/* 389 */
                    UNS8 MasterNode_Sensor_obj1402_Transmission_Type = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1402_Event_Timer = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1402_SYNC_start_value = 0x0;	/* 0 */
                    subindex MasterNode_Sensor_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1402, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1402_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1402_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1402_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1402_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1402_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1402_SYNC_start_value, NULL }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1403 = 6; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1403_COB_ID_used_by_PDO = 0x500;	/* 1280 */
                    UNS8 MasterNode_Sensor_obj1403_Transmission_Type = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1403_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1403_Event_Timer = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1403_SYNC_start_value = 0x0;	/* 0 */
                    subindex MasterNode_Sensor_Index1403[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1403, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1403_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1403_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1403_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1403_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1403_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1403_SYNC_start_value, NULL }
                     };

/* index 0x1404 :   Receive PDO 5 Parameter. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1404 = 6; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1404_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1404_Transmission_Type = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1404_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1404_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1404_Event_Timer = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1404_SYNC_start_value = 0x0;	/* 0 */
                    subindex MasterNode_Sensor_Index1404[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1404, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1404_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1404_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1404_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1404_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1404_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1404_SYNC_start_value, NULL }
                     };

/* index 0x1405 :   Receive PDO 6 Parameter. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1405 = 6; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1405_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1405_Transmission_Type = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1405_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1405_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1405_Event_Timer = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1405_SYNC_start_value = 0x0;	/* 0 */
                    subindex MasterNode_Sensor_Index1405[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1405, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1405_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1405_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1405_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1405_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1405_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1405_SYNC_start_value, NULL }
                     };

/* index 0x1406 :   Receive PDO 7 Parameter. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1406 = 6; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1406_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1406_Transmission_Type = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1406_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1406_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1406_Event_Timer = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1406_SYNC_start_value = 0x0;	/* 0 */
                    subindex MasterNode_Sensor_Index1406[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1406, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1406_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1406_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1406_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1406_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1406_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1406_SYNC_start_value, NULL }
                     };

/* index 0x1407 :   Receive PDO 8 Parameter. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1407 = 6; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1407_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1407_Transmission_Type = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1407_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1407_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1407_Event_Timer = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1407_SYNC_start_value = 0x0;	/* 0 */
                    subindex MasterNode_Sensor_Index1407[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1407, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1407_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1407_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1407_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1407_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1407_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1407_SYNC_start_value, NULL }
                     };

/* index 0x1408 :   Receive PDO 9 Parameter. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1408 = 6; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1408_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1408_Transmission_Type = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1408_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1408_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1408_Event_Timer = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1408_SYNC_start_value = 0x0;	/* 0 */
                    subindex MasterNode_Sensor_Index1408[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1408, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1408_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1408_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1408_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1408_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1408_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1408_SYNC_start_value, NULL }
                     };

/* index 0x1409 :   Receive PDO 10 Parameter. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1409 = 6; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1409_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1409_Transmission_Type = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1409_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1409_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1409_Event_Timer = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1409_SYNC_start_value = 0x0;	/* 0 */
                    subindex MasterNode_Sensor_Index1409[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1409, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1409_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1409_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1409_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1409_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1409_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1409_SYNC_start_value, NULL }
                     };

/* index 0x140A :   Receive PDO 11 Parameter. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj140A = 6; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj140A_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj140A_Transmission_Type = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj140A_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj140A_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj140A_Event_Timer = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj140A_SYNC_start_value = 0x0;	/* 0 */
                    subindex MasterNode_Sensor_Index140A[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj140A, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj140A_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj140A_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj140A_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj140A_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj140A_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj140A_SYNC_start_value, NULL }
                     };

/* index 0x140B :   Receive PDO 12 Parameter. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj140B = 6; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj140B_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj140B_Transmission_Type = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj140B_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj140B_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj140B_Event_Timer = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj140B_SYNC_start_value = 0x0;	/* 0 */
                    subindex MasterNode_Sensor_Index140B[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj140B, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj140B_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj140B_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj140B_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj140B_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj140B_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj140B_SYNC_start_value, NULL }
                     };

/* index 0x140C :   Receive PDO 13 Parameter. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj140C = 6; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj140C_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj140C_Transmission_Type = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj140C_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj140C_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj140C_Event_Timer = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj140C_SYNC_start_value = 0x0;	/* 0 */
                    subindex MasterNode_Sensor_Index140C[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj140C, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj140C_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj140C_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj140C_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj140C_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj140C_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj140C_SYNC_start_value, NULL }
                     };

/* index 0x140D :   Receive PDO 14 Parameter. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj140D = 6; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj140D_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj140D_Transmission_Type = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj140D_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj140D_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj140D_Event_Timer = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj140D_SYNC_start_value = 0x0;	/* 0 */
                    subindex MasterNode_Sensor_Index140D[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj140D, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj140D_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj140D_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj140D_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj140D_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj140D_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj140D_SYNC_start_value, NULL }
                     };

/* index 0x140E :   Receive PDO 15 Parameter. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj140E = 6; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj140E_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj140E_Transmission_Type = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj140E_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj140E_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj140E_Event_Timer = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj140E_SYNC_start_value = 0x0;	/* 0 */
                    subindex MasterNode_Sensor_Index140E[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj140E, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj140E_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj140E_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj140E_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj140E_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj140E_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj140E_SYNC_start_value, NULL }
                     };

/* index 0x140F :   Receive PDO 16 Parameter. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj140F = 6; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj140F_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj140F_Transmission_Type = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj140F_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj140F_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj140F_Event_Timer = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj140F_SYNC_start_value = 0x0;	/* 0 */
                    subindex MasterNode_Sensor_Index140F[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj140F, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj140F_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj140F_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj140F_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj140F_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj140F_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj140F_SYNC_start_value, NULL }
                     };

/* index 0x1410 :   Receive PDO 17 Parameter. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1410 = 6; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1410_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1410_Transmission_Type = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1410_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1410_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1410_Event_Timer = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1410_SYNC_start_value = 0x0;	/* 0 */
                    subindex MasterNode_Sensor_Index1410[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1410, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1410_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1410_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1410_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1410_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1410_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1410_SYNC_start_value, NULL }
                     };

/* index 0x1411 :   Receive PDO 18 Parameter. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1411 = 6; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1411_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1411_Transmission_Type = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1411_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1411_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1411_Event_Timer = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1411_SYNC_start_value = 0x0;	/* 0 */
                    subindex MasterNode_Sensor_Index1411[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1411, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1411_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1411_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1411_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1411_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1411_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1411_SYNC_start_value, NULL }
                     };

/* index 0x1412 :   Receive PDO 19 Parameter. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1412 = 6; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1412_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1412_Transmission_Type = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1412_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1412_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1412_Event_Timer = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1412_SYNC_start_value = 0x0;	/* 0 */
                    subindex MasterNode_Sensor_Index1412[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1412, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1412_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1412_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1412_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1412_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1412_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1412_SYNC_start_value, NULL }
                     };

/* index 0x1413 :   Receive PDO 20 Parameter. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1413 = 6; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1413_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1413_Transmission_Type = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1413_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1413_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1413_Event_Timer = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1413_SYNC_start_value = 0x0;	/* 0 */
                    subindex MasterNode_Sensor_Index1413[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1413, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1413_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1413_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1413_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1413_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1413_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1413_SYNC_start_value, NULL }
                     };

/* index 0x1414 :   Receive PDO 21 Parameter. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1414 = 6; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1414_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1414_Transmission_Type = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1414_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1414_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1414_Event_Timer = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1414_SYNC_start_value = 0x0;	/* 0 */
                    subindex MasterNode_Sensor_Index1414[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1414, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1414_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1414_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1414_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1414_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1414_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1414_SYNC_start_value, NULL }
                     };

/* index 0x1415 :   Receive PDO 22 Parameter. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1415 = 6; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1415_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1415_Transmission_Type = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1415_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1415_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1415_Event_Timer = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1415_SYNC_start_value = 0x0;	/* 0 */
                    subindex MasterNode_Sensor_Index1415[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1415, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1415_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1415_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1415_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1415_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1415_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1415_SYNC_start_value, NULL }
                     };

/* index 0x1416 :   Receive PDO 23 Parameter. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1416 = 6; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1416_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1416_Transmission_Type = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1416_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1416_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1416_Event_Timer = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1416_SYNC_start_value = 0x0;	/* 0 */
                    subindex MasterNode_Sensor_Index1416[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1416, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1416_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1416_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1416_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1416_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1416_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1416_SYNC_start_value, NULL }
                     };

/* index 0x1417 :   Receive PDO 24 Parameter. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1417 = 6; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1417_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1417_Transmission_Type = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1417_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1417_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1417_Event_Timer = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1417_SYNC_start_value = 0x0;	/* 0 */
                    subindex MasterNode_Sensor_Index1417[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1417, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1417_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1417_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1417_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1417_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1417_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1417_SYNC_start_value, NULL }
                     };

/* index 0x1418 :   Receive PDO 25 Parameter. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1418 = 6; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1418_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1418_Transmission_Type = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1418_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1418_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1418_Event_Timer = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1418_SYNC_start_value = 0x0;	/* 0 */
                    subindex MasterNode_Sensor_Index1418[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1418, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1418_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1418_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1418_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1418_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1418_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1418_SYNC_start_value, NULL }
                     };

/* index 0x1419 :   Receive PDO 26 Parameter. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1419 = 6; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1419_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1419_Transmission_Type = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1419_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1419_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj1419_Event_Timer = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj1419_SYNC_start_value = 0x0;	/* 0 */
                    subindex MasterNode_Sensor_Index1419[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1419, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1419_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1419_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1419_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1419_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj1419_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj1419_SYNC_start_value, NULL }
                     };

/* index 0x141A :   Receive PDO 27 Parameter. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj141A = 6; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj141A_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj141A_Transmission_Type = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj141A_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj141A_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj141A_Event_Timer = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj141A_SYNC_start_value = 0x0;	/* 0 */
                    subindex MasterNode_Sensor_Index141A[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj141A, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj141A_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj141A_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj141A_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj141A_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj141A_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj141A_SYNC_start_value, NULL }
                     };

/* index 0x141B :   Receive PDO 28 Parameter. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj141B = 6; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj141B_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj141B_Transmission_Type = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj141B_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj141B_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj141B_Event_Timer = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj141B_SYNC_start_value = 0x0;	/* 0 */
                    subindex MasterNode_Sensor_Index141B[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj141B, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj141B_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj141B_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj141B_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj141B_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj141B_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj141B_SYNC_start_value, NULL }
                     };

/* index 0x141C :   Receive PDO 29 Parameter. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj141C = 6; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj141C_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj141C_Transmission_Type = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj141C_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj141C_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj141C_Event_Timer = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj141C_SYNC_start_value = 0x0;	/* 0 */
                    subindex MasterNode_Sensor_Index141C[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj141C, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj141C_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj141C_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj141C_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj141C_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj141C_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj141C_SYNC_start_value, NULL }
                     };

/* index 0x141D :   Receive PDO 30 Parameter. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj141D = 6; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj141D_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj141D_Transmission_Type = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj141D_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj141D_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MasterNode_Sensor_obj141D_Event_Timer = 0x0;	/* 0 */
                    UNS8 MasterNode_Sensor_obj141D_SYNC_start_value = 0x0;	/* 0 */
                    subindex MasterNode_Sensor_Index141D[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj141D, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj141D_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj141D_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj141D_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj141D_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MasterNode_Sensor_obj141D_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_obj141D_SYNC_start_value, NULL }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1600 = 2; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1600[] = 
                    {
                      0x20000120,	/* 536871200 */
                      0x20010120	/* 536936736 */
                    };
                    subindex MasterNode_Sensor_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1600, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1600[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1600[1], NULL }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1601 = 2; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1601[] = 
                    {
                      0x20000220,	/* 536871456 */
                      0x20010220	/* 536936992 */
                    };
                    subindex MasterNode_Sensor_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1601, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1601[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1601[1], NULL }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1602 = 2; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1602[] = 
                    {
                      0x20000320,	/* 536871712 */
                      0x20010320	/* 536937248 */
                    };
                    subindex MasterNode_Sensor_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1602, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1602[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1602[1], NULL }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1603 = 2; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1603[] = 
                    {
                      0x20000420,	/* 536871968 */
                      0x20010420	/* 536937504 */
                    };
                    subindex MasterNode_Sensor_Index1603[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1603, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1603[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1603[1], NULL }
                     };

/* index 0x1604 :   Receive PDO 5 Mapping. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1604 = 2; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1604[] = 
                    {
                      0x20000520,	/* 536872224 */
                      0x20010520	/* 536937760 */
                    };
                    subindex MasterNode_Sensor_Index1604[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1604, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1604[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1604[1], NULL }
                     };

/* index 0x1605 :   Receive PDO 6 Mapping. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1605 = 2; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1605[] = 
                    {
                      0x20000620,	/* 536872480 */
                      0x20010620	/* 536938016 */
                    };
                    subindex MasterNode_Sensor_Index1605[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1605, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1605[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1605[1], NULL }
                     };

/* index 0x1606 :   Receive PDO 7 Mapping. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1606 = 2; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1606[] = 
                    {
                      0x20000720,	/* 536872736 */
                      0x20010720	/* 536938272 */
                    };
                    subindex MasterNode_Sensor_Index1606[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1606, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1606[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1606[1], NULL }
                     };

/* index 0x1607 :   Receive PDO 8 Mapping. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1607 = 2; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1607[] = 
                    {
                      0x20000820,	/* 536872992 */
                      0x20010820	/* 536938528 */
                    };
                    subindex MasterNode_Sensor_Index1607[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1607, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1607[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1607[1], NULL }
                     };

/* index 0x1608 :   Receive PDO 9 Mapping. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1608 = 2; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1608[] = 
                    {
                      0x20000920,	/* 536873248 */
                      0x20010920	/* 536938784 */
                    };
                    subindex MasterNode_Sensor_Index1608[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1608, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1608[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1608[1], NULL }
                     };

/* index 0x1609 :   Receive PDO 10 Mapping. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1609 = 2; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1609[] = 
                    {
                      0x20000A20,	/* 536873504 */
                      0x20010A20	/* 536939040 */
                    };
                    subindex MasterNode_Sensor_Index1609[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1609, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1609[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1609[1], NULL }
                     };

/* index 0x160A :   Receive PDO 11 Mapping. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj160A = 2; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj160A[] = 
                    {
                      0x20000B20,	/* 536873760 */
                      0x20010B20	/* 536939296 */
                    };
                    subindex MasterNode_Sensor_Index160A[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj160A, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj160A[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj160A[1], NULL }
                     };

/* index 0x160B :   Receive PDO 12 Mapping. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj160B = 2; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj160B[] = 
                    {
                      0x20000C20,	/* 536874016 */
                      0x20010C20	/* 536939552 */
                    };
                    subindex MasterNode_Sensor_Index160B[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj160B, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj160B[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj160B[1], NULL }
                     };

/* index 0x160C :   Receive PDO 13 Mapping. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj160C = 2; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj160C[] = 
                    {
                      0x20000D20,	/* 536874272 */
                      0x20010D20	/* 536939808 */
                    };
                    subindex MasterNode_Sensor_Index160C[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj160C, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj160C[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj160C[1], NULL }
                     };

/* index 0x160D :   Receive PDO 14 Mapping. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj160D = 2; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj160D[] = 
                    {
                      0x20000E20,	/* 536874528 */
                      0x20010E20	/* 536940064 */
                    };
                    subindex MasterNode_Sensor_Index160D[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj160D, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj160D[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj160D[1], NULL }
                     };

/* index 0x160E :   Receive PDO 15 Mapping. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj160E = 2; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj160E[] = 
                    {
                      0x20000F20,	/* 536874784 */
                      0x20010F20	/* 536940320 */
                    };
                    subindex MasterNode_Sensor_Index160E[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj160E, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj160E[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj160E[1], NULL }
                     };

/* index 0x160F :   Receive PDO 16 Mapping. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj160F = 2; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj160F[] = 
                    {
                      0x20001020,	/* 536875040 */
                      0x20011020	/* 536940576 */
                    };
                    subindex MasterNode_Sensor_Index160F[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj160F, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj160F[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj160F[1], NULL }
                     };

/* index 0x1610 :   Receive PDO 17 Mapping. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1610 = 2; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1610[] = 
                    {
                      0x20001120,	/* 536875296 */
                      0x20011120	/* 536940832 */
                    };
                    subindex MasterNode_Sensor_Index1610[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1610, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1610[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1610[1], NULL }
                     };

/* index 0x1611 :   Receive PDO 18 Mapping. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1611 = 2; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1611[] = 
                    {
                      0x20001220,	/* 536875552 */
                      0x20011220	/* 536941088 */
                    };
                    subindex MasterNode_Sensor_Index1611[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1611, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1611[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1611[1], NULL }
                     };

/* index 0x1612 :   Receive PDO 19 Mapping. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1612 = 2; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1612[] = 
                    {
                      0x20001320,	/* 536875808 */
                      0x20011320	/* 536941344 */
                    };
                    subindex MasterNode_Sensor_Index1612[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1612, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1612[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1612[1], NULL }
                     };

/* index 0x1613 :   Receive PDO 20 Mapping. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1613 = 2; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1613[] = 
                    {
                      0x20001420,	/* 536876064 */
                      0x20011420	/* 536941600 */
                    };
                    subindex MasterNode_Sensor_Index1613[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1613, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1613[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1613[1], NULL }
                     };

/* index 0x1614 :   Receive PDO 21 Mapping. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1614 = 2; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1614[] = 
                    {
                      0x20001520,	/* 536876320 */
                      0x20011520	/* 536941856 */
                    };
                    subindex MasterNode_Sensor_Index1614[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1614, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1614[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1614[1], NULL }
                     };

/* index 0x1615 :   Receive PDO 22 Mapping. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1615 = 2; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1615[] = 
                    {
                      0x20001620,	/* 536876576 */
                      0x20011620	/* 536942112 */
                    };
                    subindex MasterNode_Sensor_Index1615[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1615, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1615[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1615[1], NULL }
                     };

/* index 0x1616 :   Receive PDO 23 Mapping. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1616 = 2; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1616[] = 
                    {
                      0x20001720,	/* 536876832 */
                      0x20011720	/* 536942368 */
                    };
                    subindex MasterNode_Sensor_Index1616[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1616, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1616[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1616[1], NULL }
                     };

/* index 0x1617 :   Receive PDO 24 Mapping. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1617 = 2; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1617[] = 
                    {
                      0x20001820,	/* 536877088 */
                      0x20011820	/* 536942624 */
                    };
                    subindex MasterNode_Sensor_Index1617[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1617, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1617[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1617[1], NULL }
                     };

/* index 0x1618 :   Receive PDO 25 Mapping. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1618 = 2; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1618[] = 
                    {
                      0x20001920,	/* 536877344 */
                      0x20011920	/* 536942880 */
                    };
                    subindex MasterNode_Sensor_Index1618[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1618, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1618[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1618[1], NULL }
                     };

/* index 0x1619 :   Receive PDO 26 Mapping. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj1619 = 2; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj1619[] = 
                    {
                      0x20001A20,	/* 536877600 */
                      0x20011A20	/* 536943136 */
                    };
                    subindex MasterNode_Sensor_Index1619[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj1619, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1619[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj1619[1], NULL }
                     };

/* index 0x161A :   Receive PDO 27 Mapping. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj161A = 2; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj161A[] = 
                    {
                      0x20001B20,	/* 536877856 */
                      0x20011B20	/* 536943392 */
                    };
                    subindex MasterNode_Sensor_Index161A[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj161A, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj161A[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj161A[1], NULL }
                     };

/* index 0x161B :   Receive PDO 28 Mapping. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj161B = 2; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj161B[] = 
                    {
                      0x20001C20,	/* 536878112 */
                      0x20011C20	/* 536943648 */
                    };
                    subindex MasterNode_Sensor_Index161B[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj161B, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj161B[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj161B[1], NULL }
                     };

/* index 0x161C :   Receive PDO 29 Mapping. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj161C = 2; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj161C[] = 
                    {
                      0x20001D20,	/* 536878368 */
                      0x20011D20	/* 536943904 */
                    };
                    subindex MasterNode_Sensor_Index161C[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj161C, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj161C[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj161C[1], NULL }
                     };

/* index 0x161D :   Receive PDO 30 Mapping. */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj161D = 2; /* number of subindex - 1*/
                    UNS32 MasterNode_Sensor_obj161D[] = 
                    {
                      0x20001E20,	/* 536878624 */
                      0x20011E20	/* 536944160 */
                    };
                    subindex MasterNode_Sensor_Index161D[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj161D, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj161D[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterNode_Sensor_obj161D[1], NULL }
                     };

/* index 0x2000 :   Mapped variable Temperature */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj2000 = 30; /* number of subindex - 1*/
                    subindex MasterNode_Sensor_Index2000[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj2000, NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Temperature[0], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Temperature[1], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Temperature[2], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Temperature[3], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Temperature[4], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Temperature[5], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Temperature[6], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Temperature[7], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Temperature[8], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Temperature[9], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Temperature[10], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Temperature[11], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Temperature[12], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Temperature[13], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Temperature[14], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Temperature[15], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Temperature[16], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Temperature[17], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Temperature[18], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Temperature[19], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Temperature[20], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Temperature[21], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Temperature[22], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Temperature[23], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Temperature[24], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Temperature[25], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Temperature[26], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Temperature[27], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Temperature[28], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Temperature[29], NULL }
                     };

/* index 0x2001 :   Mapped variable Humidity */
                    UNS8 MasterNode_Sensor_highestSubIndex_obj2001 = 30; /* number of subindex - 1*/
                    subindex MasterNode_Sensor_Index2001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MasterNode_Sensor_highestSubIndex_obj2001, NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Humidity[0], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Humidity[1], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Humidity[2], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Humidity[3], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Humidity[4], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Humidity[5], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Humidity[6], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Humidity[7], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Humidity[8], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Humidity[9], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Humidity[10], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Humidity[11], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Humidity[12], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Humidity[13], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Humidity[14], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Humidity[15], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Humidity[16], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Humidity[17], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Humidity[18], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Humidity[19], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Humidity[20], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Humidity[21], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Humidity[22], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Humidity[23], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Humidity[24], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Humidity[25], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Humidity[26], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Humidity[27], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Humidity[28], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Humidity[29], NULL }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable MasterNode_Sensor_objdict[] = 
{
  { (subindex*)MasterNode_Sensor_Index1000,sizeof(MasterNode_Sensor_Index1000)/sizeof(MasterNode_Sensor_Index1000[0]), 0x1000},
  { (subindex*)MasterNode_Sensor_Index1001,sizeof(MasterNode_Sensor_Index1001)/sizeof(MasterNode_Sensor_Index1001[0]), 0x1001},
  { (subindex*)MasterNode_Sensor_Index1005,sizeof(MasterNode_Sensor_Index1005)/sizeof(MasterNode_Sensor_Index1005[0]), 0x1005},
  { (subindex*)MasterNode_Sensor_Index1006,sizeof(MasterNode_Sensor_Index1006)/sizeof(MasterNode_Sensor_Index1006[0]), 0x1006},
  { (subindex*)MasterNode_Sensor_Index1007,sizeof(MasterNode_Sensor_Index1007)/sizeof(MasterNode_Sensor_Index1007[0]), 0x1007},
  { (subindex*)MasterNode_Sensor_Index1016,sizeof(MasterNode_Sensor_Index1016)/sizeof(MasterNode_Sensor_Index1016[0]), 0x1016},
  { (subindex*)MasterNode_Sensor_Index1018,sizeof(MasterNode_Sensor_Index1018)/sizeof(MasterNode_Sensor_Index1018[0]), 0x1018},
  { (subindex*)MasterNode_Sensor_Index1400,sizeof(MasterNode_Sensor_Index1400)/sizeof(MasterNode_Sensor_Index1400[0]), 0x1400},
  { (subindex*)MasterNode_Sensor_Index1401,sizeof(MasterNode_Sensor_Index1401)/sizeof(MasterNode_Sensor_Index1401[0]), 0x1401},
  { (subindex*)MasterNode_Sensor_Index1402,sizeof(MasterNode_Sensor_Index1402)/sizeof(MasterNode_Sensor_Index1402[0]), 0x1402},
  { (subindex*)MasterNode_Sensor_Index1403,sizeof(MasterNode_Sensor_Index1403)/sizeof(MasterNode_Sensor_Index1403[0]), 0x1403},
  { (subindex*)MasterNode_Sensor_Index1404,sizeof(MasterNode_Sensor_Index1404)/sizeof(MasterNode_Sensor_Index1404[0]), 0x1404},
  { (subindex*)MasterNode_Sensor_Index1405,sizeof(MasterNode_Sensor_Index1405)/sizeof(MasterNode_Sensor_Index1405[0]), 0x1405},
  { (subindex*)MasterNode_Sensor_Index1406,sizeof(MasterNode_Sensor_Index1406)/sizeof(MasterNode_Sensor_Index1406[0]), 0x1406},
  { (subindex*)MasterNode_Sensor_Index1407,sizeof(MasterNode_Sensor_Index1407)/sizeof(MasterNode_Sensor_Index1407[0]), 0x1407},
  { (subindex*)MasterNode_Sensor_Index1408,sizeof(MasterNode_Sensor_Index1408)/sizeof(MasterNode_Sensor_Index1408[0]), 0x1408},
  { (subindex*)MasterNode_Sensor_Index1409,sizeof(MasterNode_Sensor_Index1409)/sizeof(MasterNode_Sensor_Index1409[0]), 0x1409},
  { (subindex*)MasterNode_Sensor_Index140A,sizeof(MasterNode_Sensor_Index140A)/sizeof(MasterNode_Sensor_Index140A[0]), 0x140A},
  { (subindex*)MasterNode_Sensor_Index140B,sizeof(MasterNode_Sensor_Index140B)/sizeof(MasterNode_Sensor_Index140B[0]), 0x140B},
  { (subindex*)MasterNode_Sensor_Index140C,sizeof(MasterNode_Sensor_Index140C)/sizeof(MasterNode_Sensor_Index140C[0]), 0x140C},
  { (subindex*)MasterNode_Sensor_Index140D,sizeof(MasterNode_Sensor_Index140D)/sizeof(MasterNode_Sensor_Index140D[0]), 0x140D},
  { (subindex*)MasterNode_Sensor_Index140E,sizeof(MasterNode_Sensor_Index140E)/sizeof(MasterNode_Sensor_Index140E[0]), 0x140E},
  { (subindex*)MasterNode_Sensor_Index140F,sizeof(MasterNode_Sensor_Index140F)/sizeof(MasterNode_Sensor_Index140F[0]), 0x140F},
  { (subindex*)MasterNode_Sensor_Index1410,sizeof(MasterNode_Sensor_Index1410)/sizeof(MasterNode_Sensor_Index1410[0]), 0x1410},
  { (subindex*)MasterNode_Sensor_Index1411,sizeof(MasterNode_Sensor_Index1411)/sizeof(MasterNode_Sensor_Index1411[0]), 0x1411},
  { (subindex*)MasterNode_Sensor_Index1412,sizeof(MasterNode_Sensor_Index1412)/sizeof(MasterNode_Sensor_Index1412[0]), 0x1412},
  { (subindex*)MasterNode_Sensor_Index1413,sizeof(MasterNode_Sensor_Index1413)/sizeof(MasterNode_Sensor_Index1413[0]), 0x1413},
  { (subindex*)MasterNode_Sensor_Index1414,sizeof(MasterNode_Sensor_Index1414)/sizeof(MasterNode_Sensor_Index1414[0]), 0x1414},
  { (subindex*)MasterNode_Sensor_Index1415,sizeof(MasterNode_Sensor_Index1415)/sizeof(MasterNode_Sensor_Index1415[0]), 0x1415},
  { (subindex*)MasterNode_Sensor_Index1416,sizeof(MasterNode_Sensor_Index1416)/sizeof(MasterNode_Sensor_Index1416[0]), 0x1416},
  { (subindex*)MasterNode_Sensor_Index1417,sizeof(MasterNode_Sensor_Index1417)/sizeof(MasterNode_Sensor_Index1417[0]), 0x1417},
  { (subindex*)MasterNode_Sensor_Index1418,sizeof(MasterNode_Sensor_Index1418)/sizeof(MasterNode_Sensor_Index1418[0]), 0x1418},
  { (subindex*)MasterNode_Sensor_Index1419,sizeof(MasterNode_Sensor_Index1419)/sizeof(MasterNode_Sensor_Index1419[0]), 0x1419},
  { (subindex*)MasterNode_Sensor_Index141A,sizeof(MasterNode_Sensor_Index141A)/sizeof(MasterNode_Sensor_Index141A[0]), 0x141A},
  { (subindex*)MasterNode_Sensor_Index141B,sizeof(MasterNode_Sensor_Index141B)/sizeof(MasterNode_Sensor_Index141B[0]), 0x141B},
  { (subindex*)MasterNode_Sensor_Index141C,sizeof(MasterNode_Sensor_Index141C)/sizeof(MasterNode_Sensor_Index141C[0]), 0x141C},
  { (subindex*)MasterNode_Sensor_Index141D,sizeof(MasterNode_Sensor_Index141D)/sizeof(MasterNode_Sensor_Index141D[0]), 0x141D},
  { (subindex*)MasterNode_Sensor_Index1600,sizeof(MasterNode_Sensor_Index1600)/sizeof(MasterNode_Sensor_Index1600[0]), 0x1600},
  { (subindex*)MasterNode_Sensor_Index1601,sizeof(MasterNode_Sensor_Index1601)/sizeof(MasterNode_Sensor_Index1601[0]), 0x1601},
  { (subindex*)MasterNode_Sensor_Index1602,sizeof(MasterNode_Sensor_Index1602)/sizeof(MasterNode_Sensor_Index1602[0]), 0x1602},
  { (subindex*)MasterNode_Sensor_Index1603,sizeof(MasterNode_Sensor_Index1603)/sizeof(MasterNode_Sensor_Index1603[0]), 0x1603},
  { (subindex*)MasterNode_Sensor_Index1604,sizeof(MasterNode_Sensor_Index1604)/sizeof(MasterNode_Sensor_Index1604[0]), 0x1604},
  { (subindex*)MasterNode_Sensor_Index1605,sizeof(MasterNode_Sensor_Index1605)/sizeof(MasterNode_Sensor_Index1605[0]), 0x1605},
  { (subindex*)MasterNode_Sensor_Index1606,sizeof(MasterNode_Sensor_Index1606)/sizeof(MasterNode_Sensor_Index1606[0]), 0x1606},
  { (subindex*)MasterNode_Sensor_Index1607,sizeof(MasterNode_Sensor_Index1607)/sizeof(MasterNode_Sensor_Index1607[0]), 0x1607},
  { (subindex*)MasterNode_Sensor_Index1608,sizeof(MasterNode_Sensor_Index1608)/sizeof(MasterNode_Sensor_Index1608[0]), 0x1608},
  { (subindex*)MasterNode_Sensor_Index1609,sizeof(MasterNode_Sensor_Index1609)/sizeof(MasterNode_Sensor_Index1609[0]), 0x1609},
  { (subindex*)MasterNode_Sensor_Index160A,sizeof(MasterNode_Sensor_Index160A)/sizeof(MasterNode_Sensor_Index160A[0]), 0x160A},
  { (subindex*)MasterNode_Sensor_Index160B,sizeof(MasterNode_Sensor_Index160B)/sizeof(MasterNode_Sensor_Index160B[0]), 0x160B},
  { (subindex*)MasterNode_Sensor_Index160C,sizeof(MasterNode_Sensor_Index160C)/sizeof(MasterNode_Sensor_Index160C[0]), 0x160C},
  { (subindex*)MasterNode_Sensor_Index160D,sizeof(MasterNode_Sensor_Index160D)/sizeof(MasterNode_Sensor_Index160D[0]), 0x160D},
  { (subindex*)MasterNode_Sensor_Index160E,sizeof(MasterNode_Sensor_Index160E)/sizeof(MasterNode_Sensor_Index160E[0]), 0x160E},
  { (subindex*)MasterNode_Sensor_Index160F,sizeof(MasterNode_Sensor_Index160F)/sizeof(MasterNode_Sensor_Index160F[0]), 0x160F},
  { (subindex*)MasterNode_Sensor_Index1610,sizeof(MasterNode_Sensor_Index1610)/sizeof(MasterNode_Sensor_Index1610[0]), 0x1610},
  { (subindex*)MasterNode_Sensor_Index1611,sizeof(MasterNode_Sensor_Index1611)/sizeof(MasterNode_Sensor_Index1611[0]), 0x1611},
  { (subindex*)MasterNode_Sensor_Index1612,sizeof(MasterNode_Sensor_Index1612)/sizeof(MasterNode_Sensor_Index1612[0]), 0x1612},
  { (subindex*)MasterNode_Sensor_Index1613,sizeof(MasterNode_Sensor_Index1613)/sizeof(MasterNode_Sensor_Index1613[0]), 0x1613},
  { (subindex*)MasterNode_Sensor_Index1614,sizeof(MasterNode_Sensor_Index1614)/sizeof(MasterNode_Sensor_Index1614[0]), 0x1614},
  { (subindex*)MasterNode_Sensor_Index1615,sizeof(MasterNode_Sensor_Index1615)/sizeof(MasterNode_Sensor_Index1615[0]), 0x1615},
  { (subindex*)MasterNode_Sensor_Index1616,sizeof(MasterNode_Sensor_Index1616)/sizeof(MasterNode_Sensor_Index1616[0]), 0x1616},
  { (subindex*)MasterNode_Sensor_Index1617,sizeof(MasterNode_Sensor_Index1617)/sizeof(MasterNode_Sensor_Index1617[0]), 0x1617},
  { (subindex*)MasterNode_Sensor_Index1618,sizeof(MasterNode_Sensor_Index1618)/sizeof(MasterNode_Sensor_Index1618[0]), 0x1618},
  { (subindex*)MasterNode_Sensor_Index1619,sizeof(MasterNode_Sensor_Index1619)/sizeof(MasterNode_Sensor_Index1619[0]), 0x1619},
  { (subindex*)MasterNode_Sensor_Index161A,sizeof(MasterNode_Sensor_Index161A)/sizeof(MasterNode_Sensor_Index161A[0]), 0x161A},
  { (subindex*)MasterNode_Sensor_Index161B,sizeof(MasterNode_Sensor_Index161B)/sizeof(MasterNode_Sensor_Index161B[0]), 0x161B},
  { (subindex*)MasterNode_Sensor_Index161C,sizeof(MasterNode_Sensor_Index161C)/sizeof(MasterNode_Sensor_Index161C[0]), 0x161C},
  { (subindex*)MasterNode_Sensor_Index161D,sizeof(MasterNode_Sensor_Index161D)/sizeof(MasterNode_Sensor_Index161D[0]), 0x161D},
  { (subindex*)MasterNode_Sensor_Index2000,sizeof(MasterNode_Sensor_Index2000)/sizeof(MasterNode_Sensor_Index2000[0]), 0x2000},
  { (subindex*)MasterNode_Sensor_Index2001,sizeof(MasterNode_Sensor_Index2001)/sizeof(MasterNode_Sensor_Index2001[0]), 0x2001},
};

const indextable * MasterNode_Sensor_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode)
{
	(void)d;
	int i;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1005: i = 2;break;
		case 0x1006: i = 3;break;
		case 0x1007: i = 4;break;
		case 0x1016: i = 5;break;
		case 0x1018: i = 6;break;
		case 0x1400: i = 7;break;
		case 0x1401: i = 8;break;
		case 0x1402: i = 9;break;
		case 0x1403: i = 10;break;
		case 0x1404: i = 11;break;
		case 0x1405: i = 12;break;
		case 0x1406: i = 13;break;
		case 0x1407: i = 14;break;
		case 0x1408: i = 15;break;
		case 0x1409: i = 16;break;
		case 0x140A: i = 17;break;
		case 0x140B: i = 18;break;
		case 0x140C: i = 19;break;
		case 0x140D: i = 20;break;
		case 0x140E: i = 21;break;
		case 0x140F: i = 22;break;
		case 0x1410: i = 23;break;
		case 0x1411: i = 24;break;
		case 0x1412: i = 25;break;
		case 0x1413: i = 26;break;
		case 0x1414: i = 27;break;
		case 0x1415: i = 28;break;
		case 0x1416: i = 29;break;
		case 0x1417: i = 30;break;
		case 0x1418: i = 31;break;
		case 0x1419: i = 32;break;
		case 0x141A: i = 33;break;
		case 0x141B: i = 34;break;
		case 0x141C: i = 35;break;
		case 0x141D: i = 36;break;
		case 0x1600: i = 37;break;
		case 0x1601: i = 38;break;
		case 0x1602: i = 39;break;
		case 0x1603: i = 40;break;
		case 0x1604: i = 41;break;
		case 0x1605: i = 42;break;
		case 0x1606: i = 43;break;
		case 0x1607: i = 44;break;
		case 0x1608: i = 45;break;
		case 0x1609: i = 46;break;
		case 0x160A: i = 47;break;
		case 0x160B: i = 48;break;
		case 0x160C: i = 49;break;
		case 0x160D: i = 50;break;
		case 0x160E: i = 51;break;
		case 0x160F: i = 52;break;
		case 0x1610: i = 53;break;
		case 0x1611: i = 54;break;
		case 0x1612: i = 55;break;
		case 0x1613: i = 56;break;
		case 0x1614: i = 57;break;
		case 0x1615: i = 58;break;
		case 0x1616: i = 59;break;
		case 0x1617: i = 60;break;
		case 0x1618: i = 61;break;
		case 0x1619: i = 62;break;
		case 0x161A: i = 63;break;
		case 0x161B: i = 64;break;
		case 0x161C: i = 65;break;
		case 0x161D: i = 66;break;
		case 0x2000: i = 67;break;
		case 0x2001: i = 68;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &MasterNode_Sensor_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status MasterNode_Sensor_PDO_status[1] = {s_PDO_status_Initializer};

const quick_index MasterNode_Sensor_firstIndex = {
  0, /* SDO_SVR */
  0, /* SDO_CLT */
  7, /* PDO_RCV */
  37, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const quick_index MasterNode_Sensor_lastIndex = {
  0, /* SDO_SVR */
  0, /* SDO_CLT */
  36, /* PDO_RCV */
  66, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const UNS16 MasterNode_Sensor_ObjdictSize = sizeof(MasterNode_Sensor_objdict)/sizeof(MasterNode_Sensor_objdict[0]); 

CO_Data MasterNode_Sensor_Data = CANOPEN_NODE_DATA_INITIALIZER(MasterNode_Sensor);

